notifications:
  email: false
language: c 

before_script:
  - WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused --no-dns-cache --timeout 300"
  - sudo apt-get -qq update

  ## Install doxygen
  - if [ ${BUILD_CATEGORY:-0} = doxygen ] ; then
      sudo add-apt-repository ppa:libreoffice/libreoffice-4-4 -y && sudo apt-get -qq update &&
      sudo apt-get --no-install-suggests --no-install-recommends -qq install doxygen  &&
      doxygen --version ;
    fi	

  ## Install avr toolchain
  - sudo apt-get -qq install gcc-avr avr-libc

  ## Install 32-bit compatibility libraries
  - sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386
      libstdc++5:i386 libstdc++6:i386	  

  ## Install CFV1 GCC toolchain 
  - if [ ${BUILD_ARCH:-0} = cfv1 ] ; then  
      $WGET http://ftp.gnu.org/gnu/gmp/gmp-5.1.3.tar.gz &&
      tar -xvf gmp-5.1.3.tar.gz &&
      cd gmp-5.1.3 &&
      ./configure &&
      make -j 6 &&
      sudo make install &&
      cd .. &&
      $WGET http://www.mpfr.org/mpfr-current/mpfr-3.1.3.tar.bz2 &&
      bzcat mpfr-3.1.3.tar.bz2 | tar -xf - &&
      cd mpfr-3.1.3 &&
      ./configure &&
      make -j 6 &&
      sudo make install &&
      cd .. &&
      $WGET ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz &&
      tar -xvf mpc-1.0.3.tar.gz &&
      cd mpc-1.0.3 &&
      ./configure &&
      make -j 6 &&
      sudo make install &&
      cd .. &&	  
      sudo ldconfig &&
      sudo depmod -a &&
      $WGET http://ftp.gnu.org/gnu/gcc/gcc-4.6.3/gcc-core-4.6.3.tar.bz2 &&
      tar xvjf gcc-core-4.6.3.tar.bz2 &&
      cd gcc-4.6.3 &&
      mkdir build &&
      cd build &&      
      CFLAGS="-Wno-error" ../configure --target=m68k-elf --prefix=${INSTPREFIX} --enable-languages=c --with-newlib --disable-libmudflap --disable-libssp --disable-libgomp --disable-libstdcxx-pch --disable-threads --with-gnu-as --with-gnu-ld --disable-nls --with-headers=yes --disable-checking --without-headers &&
      CFLAGS="-Wno-error" make &&
      sudo PATH=${PATH}:${INSTPREFIX} make install &&
      cd .. &&
      cd .. &&
      $WGET ftp://sources.redhat.com/pub/newlib/newlib-1.20.0.tar.gz &&
      tar -xvf newlib-1.20.0.tar.gz &&
      cd newlib-1.20.0 &&
      mkdir m68k-obj &&
      cd m68k-obj &&
      ../configure --target=m68k-elf --prefix=${INSTPREFIX} --enable-newlib-reent-small --disable-malloc-debugging --enable-newlib-multithread --disable-newlib-io-float --disable-newlib-supplied-syscalls --disable-newlib-io-c99-formats --disable-newlib-mb --disable-newlib-atexit-alloc --enable-target-optspace --disable-shared --enable-static --enable-fast-install &&
      make -j 6 &&
      sudo PATH=${PATH}:${INSTPREFIX} make install &&
      m68k-elf-gcc -v ;
    fi

script:
  - "make -C tests/$BUILD_TYPE all"

env:
  ## This magically kick-off parallel jobs for each of the for the sets
  ## of environment variable defined below
  ## - BUILD_TYPE='doxygen'  BUILD_CATEGORY='doxygen'
  - BUILD_TYPE='compile-cfv1-port' BUILD_CATEGORY='compile' BUILD_ARCH='cfv1'
  - BUILD_TYPE='compile-avr-port' BUILD_CATEGORY='compile'
