notifications:
  email: false
language: c #NOTE: this will set CC=gcc which might cause trouble

before_script:
  - WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused --no-dns-cache --timeout 300"
  - sudo apt-get -qq update

  ## Install doxygen
  - if [ ${BUILD_CATEGORY:-0} = doxygen ] ; then
      sudo add-apt-repository ppa:libreoffice/libreoffice-4-4 -y && sudo apt-get -qq update &&
      sudo apt-get --no-install-suggests --no-install-recommends -qq install doxygen  &&
      doxygen --version ;
    fi	

  ## Install avr toolchain
  - sudo apt-get -qq install gcc-avr avr-libc

  ## Install 32-bit compatibility libraries
  - sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386
      libstdc++5:i386 libstdc++6:i386	  

  ## Install CFV1 GCC toolchain 
  - if [ ${BUILD_ARCH:-0} = cfv1 ] ; then	     
      $WGET https://raw.githubusercontent.com/brtos/examples/master/tools/coldfire-gcc.tar.bz2 &&
      tar xjf coldfire*.tar.bz2 -C /tmp/ &&
      /tmp/coldfire/bin/m68k-elf-gcc --version &&
      sudo cp -f -r /tmp/coldfire/* /usr/local/ &&
      rm -rf /tmp/coldfire coldfire*.tar.bz2   &&
      m68k-elf-gcc --version; 
    fi
	
    - if [ ${BUILD_ARCH:-0} = avr ] ; then	     
      avr-gcc --version; 
    fi


script:
  ## tests/Makefile handles most of generic logic
  - "make -C tests/??-$BUILD_TYPE RUNALL=true summary"

after_script:
  ## Print a basic summary
  - "echo 'Summary:'; cat tests/??-$BUILD_TYPE/summary"
  - "FAILS=`grep -c  ' FAIL ' tests/??-$BUILD_TYPE/summary`"
  ## This will detect whether the build should pass or fail
  - "test $FAILS -eq 0; exit $?"

env:
  ## This magically kick-off parallel jobs for each of the for the sets
  ## of environment variable defined below
  ## - BUILD_TYPE='doxygen'  BUILD_CATEGORY='doxygen'
  - BUILD_TYPE='compile-cfv1-port' BUILD_CATEGORY='compile' BUILD_ARCH='cfv1'
  - BUILD_TYPE='compile-avr-port' BUILD_CATEGORY='compile' BUILD_ARCH='avr'
